name: grind_lab
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_route: ^9.2.2
  freezed: ^2.5.7
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  auto_route_generator: ^9.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/



